[package]
name = "oxidant-rust-tools"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
oxidant-core.workspace = true
oxidant-tools.workspace = true

tokio.workspace = true
async-trait.workspace = true
futures.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
syn.workspace = true
quote.workspace = true
proc-macro2.workspace = true
lsp-types.workspace = true
camino.workspace = true
cargo_metadata.workspace = true
regex.workspace = true

[dev-dependencies]
tempfile.workspace = true
tokio = { workspace = true }
tokio-util.workspace = true
dunce.workspace = true
