[package]
name = "oxidant-gui"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
oxidant-core.workspace = true
oxidant-config.workspace = true
oxidant-spec-tools.workspace = true
oxidant-vcs.workspace = true

tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
anyhow.workspace = true
thiserror.workspace = true
tracing.workspace = true
eframe.workspace = true
egui.workspace = true
egui_dock.workspace = true
egui_commonmark.workspace = true
syntect.workspace = true
camino.workspace = true
